apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - account-service-dev.yaml
  - chat-service-dev.yaml
  - ticket-service-dev.yaml
  - trade-service-dev.yaml
  - cs-service-dev.yaml
